version: '3.8'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
    env_file:
      - ./apps/users/.env
    volumes:
      - ./apps/users:/usr/src/apps/users
      - ./common:/usr/src/apps/users/common
    ports:
      - 8002:8002
    depends_on:
      - postgres-db
      - redis
    networks:
      - kong-net
    command: >
      bash -c "sleep 5 &&
              alembic -c /usr/src/apps/users/alembic.ini upgrade head &&
              uvicorn main:app --host 0.0.0.0 --port 8002 --reload"

  trips:
    build:
      context: .
      dockerfile: ./apps/trips/Dockerfile
    env_file:
      - ./apps/trips/.env
    volumes:
      - ./apps/trips:/usr/src/apps/trips
      - ./common:/usr/src/apps/trips/common
    ports:
      - 8003:8003
    depends_on:
      - mongodb
      - redis
    networks:
      - kong-net
    command: >
      bash -c "sleep 5 &&
              uvicorn main:app --host 0.0.0.0 --port 8003 --reload"

  expenses:
    build:
      context: .
      dockerfile: ./apps/expenses/Dockerfile
    env_file:
      - ./apps/expenses/.env
    volumes:
      - ./apps/expenses:/usr/src/apps/expenses
      - ./common:/usr/src/apps/expenses/common
    ports:
      - 8004:8004
    depends_on:
      - mongodb
      - redis
    networks:
      - kong-net
    command: >
      bash -c "sleep 5 &&
              uvicorn main:app --host 0.0.0.0 --port 8004 --reload"

  reimbursements:
    build:
      context: .
      dockerfile: ./apps/reimbursements/Dockerfile
    env_file:
      - ./apps/reimbursements/.env
    volumes:
      - ./apps/reimbursements:/usr/src/apps/reimbursements
      - ./common:/usr/src/apps/reimbursements/common
    ports:
      - 8005:8005
    depends_on:
      - postgres-db
      - redis
    networks:
      - kong-net
    command: >
      bash -c "sleep 5 &&
              alembic -c /usr/src/apps/reimbursements/alembic.ini upgrade head &&
              uvicorn main:app --host 0.0.0.0 --port 8005 --reload"

  reimbursements-worker:
    build: 
      context: .
      dockerfile: ./apps/workers/reimbursements/Dockerfile
    env_file:
      - ./apps/workers/reimbursements/.env
    depends_on:
      - rabbitmq
    restart: "on-failure"
    networks:
      - kong-net

  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-db
    networks:
      - kong-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - kong-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - kong-net

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - kong-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - kong-net
