version: '3.8'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
    env_file:
      - ./apps/users/.env
    volumes:
      - ./apps/users:/usr/src/apps/users
      - ./common:/usr/src/apps/users/common
    ports:
      - 8002:8002
    depends_on:
      - postgres-db
      - redis
    networks:
      - kong-net
    command: >
      bash -c "sleep 5 &&
              alembic -c /usr/src/apps/users/alembic.ini upgrade head &&
              uvicorn main:app --host 0.0.0.0 --port 8002 --reload"

  trips:
    build:
      context: .
      dockerfile: ./apps/trips/Dockerfile
    env_file:
      - ./apps/trips/.env
    volumes:
      - ./apps/trips:/usr/src/apps/trips
      - ./common:/usr/src/apps/trips/common
    ports:
      - 8003:8003
    depends_on:
      - postgres-db
      - redis
    networks:
      - kong-net
    command: >
      bash -c "sleep 5 &&
              uvicorn main:app --host 0.0.0.0 --port 8003 --reload"

  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-db
    networks:
      - kong-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - kong-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - kong-net
